import { Router, type Router as RouterType } from 'express';
import healthRoutes from './health.routes';
import authRoutes from './auth.routes';
import userRoutes from './user.routes';
import paymentTypeRoutes from './payment-type.routes';
import paymentRoutes from './payment.routes';
import expenseCategoryRoutes from './expense-category.routes';
import expenseRoutes from './expense.routes';
import transactionRoutes from './transaction.routes';
import uploadRoutes from './upload.routes';
import notificationRoutes from './notification.routes';
import messageTemplateRoutes from './message-template.routes';
import arrearsReminderRoutes from './arrears-reminder.routes';
import whatsappDeliveryRoutes from './whatsapp-delivery.routes';
import securityRoutes from './security.routes';
import internalRoutes from './internal.routes';
import reportRoutes from './report.routes';
import budgetRoutes from './budget.routes';
import householdRoutes from './household.routes';
import appVersionRoutes from './app-version.routes';

const router: RouterType = Router();

router.use(healthRoutes);
router.use(appVersionRoutes);
router.use('/auth', authRoutes);
router.use('/users', userRoutes);
router.use('/payment-types', paymentTypeRoutes);
router.use('/payments', paymentRoutes);
router.use('/expense-categories', expenseCategoryRoutes);
router.use('/expenses', expenseRoutes);
router.use('/transactions', transactionRoutes);
router.use('/upload', uploadRoutes);
router.use('/notifications', notificationRoutes);
router.use('/message-templates', messageTemplateRoutes);
router.use('/arrears-reminders', arrearsReminderRoutes);
router.use('/whatsapp-deliveries', whatsappDeliveryRoutes);
router.use('/security', securityRoutes);
router.use('/internal', internalRoutes);
router.use('/reports', reportRoutes);
router.use('/budgets', budgetRoutes);
router.use('/households', householdRoutes);

export default router;
